/// Flutter icons Rider
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Rider
///      fonts:
///       - asset: fonts/Rider.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Rider {
  Rider._();

  static const _kFontFam = 'Rider';
  static const _kFontPkg = null;

  static const IconData rider = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData group = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racing_flag_2 = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData classic = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cafeRacer = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bobber = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cruiser = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sports = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scooter = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData city = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retro = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData retro2 = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData racer = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
